name: Build

on:
  push:
    branches:
      - main

  pull_request:

env:
  DOTNET_VERSION: 9.0.x

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore BrasilLauncher.slnx

      - name: Build
        run: dotnet build BrasilLauncher.slnx -c Release --no-restore
